### ISSUE TITLE
Missing Package

### ISSUE THREAD

**Issue by nerdromancer** [jumpbytehq/cordova-jb-plugin-panframe#2]
When compiling an Android project in Cordova with this plugin installed, I get this:

SimpleStreamPlayerActivity.java:28: error: package com.cappital.digitalfood does not exist

I see this on line 28:

import com.cappital.digitalfood.R;

But I don't see that package anywhere in the libs.

**Comment by vintesh** [comment]
Thanks, @nerdromancer for bringing this up.
We have now removed that unwanted import from the file, it should now work, if not then please open project in Android Studio & import your generated `R.java` file.
